branch-defaults:
  master:
    environment: palindrome
  dev:
    environment: palindrome-dev
global:
  application_name: palindrome
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
